// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3uLU_3eec8Mrya4ALs9BA5ZvgC1roZWY',
    appId: '1:263584274027:web:8e460a92c303812155c32e',
    messagingSenderId: '263584274027',
    projectId: 'expense-tracker-5a185',
    authDomain: 'expense-tracker-5a185.firebaseapp.com',
    databaseURL: 'https://expense-tracker-5a185-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-5a185.appspot.com',
    measurementId: 'G-969G9QKBMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBcCSSnhgz6SI60EqzDLtZeSLSoyNM--Y',
    appId: '1:263584274027:android:7d052baac9ab664055c32e',
    messagingSenderId: '263584274027',
    projectId: 'expense-tracker-5a185',
    databaseURL: 'https://expense-tracker-5a185-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-5a185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5qUg30CeCulEmSen7g88Yf_2U1OgHpgY',
    appId: '1:263584274027:ios:850699eeb284ad0155c32e',
    messagingSenderId: '263584274027',
    projectId: 'expense-tracker-5a185',
    databaseURL: 'https://expense-tracker-5a185-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-5a185.appspot.com',
    iosClientId: '263584274027-5hh1dbkvt2plpcjolk38jo22ovkrl0j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5qUg30CeCulEmSen7g88Yf_2U1OgHpgY',
    appId: '1:263584274027:ios:850699eeb284ad0155c32e',
    messagingSenderId: '263584274027',
    projectId: 'expense-tracker-5a185',
    databaseURL: 'https://expense-tracker-5a185-default-rtdb.firebaseio.com',
    storageBucket: 'expense-tracker-5a185.appspot.com',
    iosClientId: '263584274027-5hh1dbkvt2plpcjolk38jo22ovkrl0j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
